-- MySQL Script generated by MySQL Workbench
-- Sat Jan 15 17:32:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zaposlenik
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zaposlenik` ;

-- -----------------------------------------------------
-- Schema zaposlenik
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zaposlenik` DEFAULT CHARACTER SET utf8 ;
USE `zaposlenik` ;

-- -----------------------------------------------------
-- Table `zaposlenik`.`dobavljac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`dobavljac` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`dobavljac` (
  `id_dobavljac` INT NOT NULL,
  `naziv_dobavljaca` VARCHAR(45) NULL,
  `adresa_dobavljaca` VARCHAR(45) NULL,
  `kontakt_dobavljaca` VARCHAR(45) NULL,
  PRIMARY KEY (`id_dobavljac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zaposlenik`.`kupac`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`kupac` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`kupac` (
  `id_kupac` INT NOT NULL,
  `ime_kupca` VARCHAR(45) NULL,
  `prezime_kupca` VARCHAR(45) NULL,
  `adresa_kupca` VARCHAR(45) NULL,
  `e-mail` VARCHAR(45) NULL,
  `kontakt` VARCHAR(45) NULL,
  PRIMARY KEY (`id_kupac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zaposlenik`.`kupuje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`kupuje` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`kupuje` (
  `id_kupac` INT NOT NULL,
  `id_proizvod` INT NOT NULL,
  PRIMARY KEY (`id_kupac`, `id_proizvod`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_kupac`)
    REFERENCES `zaposlenik`.`kupac` (`id_kupac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_proizvod`)
    REFERENCES `zaposlenik`.`proizvod` (`id_proizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk2_idx` ON `zaposlenik`.`kupuje` (`id_proizvod` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`odjel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`odjel` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`odjel` (
  `id_odjel` INT NOT NULL,
  `naziv_odjela` VARCHAR(45) NULL,
  PRIMARY KEY (`id_odjel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zaposlenik`.`proizvod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`proizvod` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`proizvod` (
  `id_proizvod` INT NOT NULL,
  `naziv_proizvoda` VARCHAR(45) NULL,
  `cijena_proizvoda` FLOAT NULL,
  `id_odjel` INT NOT NULL,
  `id_dobavljac` INT NOT NULL,
  PRIMARY KEY (`id_proizvod`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_dobavljac`)
    REFERENCES `zaposlenik`.`dobavljac` (`id_dobavljac`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_odjel`)
    REFERENCES `zaposlenik`.`odjel` (`id_odjel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk1_idx` ON `zaposlenik`.`proizvod` (`id_dobavljac` ASC) VISIBLE;

CREATE INDEX `fk2_idx` ON `zaposlenik`.`proizvod` (`id_odjel` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`racun` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`racun` (
  `id_racun` INT NOT NULL,
  `nacin_placanja` VARCHAR(45) NULL,
  `id_zaposlenik` INT NULL,
  PRIMARY KEY (`id_racun`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_zaposlenik`)
    REFERENCES `zaposlenik`.`zaposlenik` (`id_zaposlenik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk1_idx` ON `zaposlenik`.`racun` (`id_zaposlenik` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`reklamacija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`reklamacija` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`reklamacija` (
  `id_reklamacija` INT NOT NULL,
  `datum_reklamacije` DATE NULL,
  `id_proizvod` INT NOT NULL,
  `kolicina` INT NULL,
  `cijena` FLOAT NULL,
  `iznos` FLOAT NULL,
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_proizvod`)
    REFERENCES `zaposlenik`.`proizvod` (`id_proizvod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk1_idx` ON `zaposlenik`.`reklamacija` (`id_proizvod` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`sadrži`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`sadrži` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`sadrži` (
  `id_odjel` INT NOT NULL,
  `id_trgovina` INT NOT NULL,
  PRIMARY KEY (`id_odjel`, `id_trgovina`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_odjel`)
    REFERENCES `zaposlenik`.`odjel` (`id_odjel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_trgovina`)
    REFERENCES `zaposlenik`.`trgovina` (`id_trgovina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk2_idx` ON `zaposlenik`.`sadrži` (`id_trgovina` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`se nalazi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`se nalazi` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`se nalazi` (
  `id_racun` INT NOT NULL,
  `id_proizvod` INT NOT NULL,
  `kolicina` INT NULL,
  `cijena` FLOAT NULL,
  `iznos` FLOAT NULL,
  PRIMARY KEY (`id_racun`, `id_proizvod`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_racun`)
    REFERENCES `zaposlenik`.`racun` (`id_racun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk2`
    FOREIGN KEY (`id_proizvod`)
    REFERENCES `zaposlenik`.`proizvod` (`id_proizvod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk2_idx` ON `zaposlenik`.`se nalazi` (`id_proizvod` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `zaposlenik`.`trgovina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`trgovina` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`trgovina` (
  `id_trgovina` INT NOT NULL,
  `naziv_trgovine` VARCHAR(45) NULL,
  `broj_djelatnika` INT NULL,
  `datum_osnutka` DATE NULL,
  PRIMARY KEY (`id_trgovina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zaposlenik`.`zaposlenik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zaposlenik`.`zaposlenik` ;

CREATE TABLE IF NOT EXISTS `zaposlenik`.`zaposlenik` (
  `id_zaposlenik` INT NOT NULL,
  `ime_zaposlenika` VARCHAR(45) NOT NULL,
  `prezime_zaposlenika` VARCHAR(45) NULL,
  `adresa_zaposlenika` VARCHAR(45) NULL,
  `kontakt_zaposlenika` VARCHAR(45) NULL,
  `id_trgovina` INT NOT NULL,
  PRIMARY KEY (`id_zaposlenik`),
  CONSTRAINT `fk1`
    FOREIGN KEY (`id_trgovina`)
    REFERENCES `zaposlenik`.`trgovina` (`id_trgovina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk1_idx` ON `zaposlenik`.`zaposlenik` (`id_trgovina` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
